### ISSUE TITLE
java.lang.UnsupportedOperationException in Wildfly

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/datasafe#187]
Technical issue:

·         I can create service, register user, save, read & delete the file using adorsys in a java standalone application.

·         Same way I tried using wildfly server as a web application, I have created the services but I am getting the following exception while try to register the user,

java.lang.UnsupportedOperationException

                at java.security.KeyStoreSpi.engineLoad(KeyStoreSpi.java:418)

                at java.security.KeyStore.load(KeyStore.java:1479)

                at de.adorsys.keymanagement.bouncycastle.adapter.services.persist.DefaultKeyStoreOperImpl.createBCFKSKeystore(DefaultKeyStoreOperImpl.java:176)

                at de.adorsys.keymanagement.bouncycastle.adapter.services.persist.DefaultKeyStoreOperImpl.generate(DefaultKeyStoreOperImpl.java:88)

                at de.adorsys.keymanagement.bouncycastle.adapter.services.persist.DefaultKeyStoreOperImpl.generate(DefaultKeyStoreOperImpl.java:54)

                at de.adorsys.keymanagement.bouncycastle.adapter.services.persist.DefaultKeyStoreOperImpl.generate(DefaultKeyStoreOperImpl.java:48)

                at de.adorsys.datasafe.encrypiton.impl.keystore.KeyStoreServiceImpl.createKeyStore(KeyStoreServiceImpl.java:105)

                at de.adorsys.datasafe.encrypiton.impl.keystore.KeyStoreServiceImplRuntimeDelegatable.createKeyStore(KeyStoreServiceImplRuntimeDelegatable.java:57)

                at de.adorsys.datasafe.encrypiton.impl.keystore.KeyStoreServiceImpl.createKeyStore(KeyStoreServiceImpl.java:65)

                at de.adorsys.datasafe.encrypiton.impl.keystore.KeyStoreServiceImplRuntimeDelegatable.createKeyStore(KeyStoreServiceImplRuntimeDelegatable.java:47)

                at de.adorsys.datasafe.directory.impl.profile.keys.DocumentKeyStoreOperationsImpl.createAndWriteKeyStore(DocumentKeyStoreOperationsImpl.java:90)

                at de.adorsys.datasafe.directory.impl.profile.keys.DocumentKeyStoreOperationsImplRuntimeDelegatable.createAndWriteKeyStore(DocumentKeyStoreOperationsImplRuntimeDelegatable.java:65)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImpl.createDocumentKeystore(ProfileRegistrationServiceImpl.java:99)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImplRuntimeDelegatable.createDocumentKeystore(ProfileRegistrationServiceImplRuntimeDelegatable.java:72)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImpl.createAllAllowableKeystores(ProfileRegistrationServiceImpl.java:92)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImplRuntimeDelegatable.createAllAllowableKeystores(ProfileRegistrationServiceImplRuntimeDelegatable.java:63)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImpl.registerUsingDefaults(ProfileRegistrationServiceImpl.java:118)

                at de.adorsys.datasafe.directory.impl.profile.operations.actions.ProfileRegistrationServiceImplRuntimeDelegatable.registerUsingDefaults(ProfileRegistrationServiceImplRuntimeDelegatable.java:90)

                at de.adorsys.datasafe.directory.impl.profile.operations.DFSBasedProfileStorageImpl.registerUsingDefaults(DFSBasedProfileStorageImpl.java:22)

**Comment by valb3r** [comment]
Sample WildFly deployments:
1. OpenJDK https://github.com/valb3r/datasafe-wildfly-test/tree/wildfly-11-openjdk
1. Oracle JDK https://github.com/valb3r/datasafe-wildfly-test/tree/wildfly-11-oracle-jdk8
No issues detected with configurations from these.
